@Connect_HostAddress = http://localhost:5053

POST {{Connect_HostAddress}}/api/auth/register
Accept: application/json
Content-Type: application/json
{
    "firstName": "Ahmed",
    "lastName": "Roshdi",
    "userName": "ahmedrooshdii",
    "email": "ahmedrooshdii@gmail.com",
    "password": "Ahmed@123"
}

###

POST {{Connect_HostAddress}}/api/auth/register
Accept: application/json
Content-Type: application/json
{
    "firstName": "Manar",
    "lastName": "Mohamed",
    "userName": "manar.mohamed",
    "email": ".manar@gmail.com",
    "password": "Manar@123"
}

###

POST {{Connect_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json
{
    "email": "ahmedrooshdii@gmail.com",
    "password": "Ahmed@123Engineer"
}

###